### ISSUE TITLE
cannot build on ubuntu studio 14.04

### ISSUE THREAD

**Issue by VinceLewis** [jeremysalwen/So-synth-LV2#1]
Hi, am trying to build this using the command dpkg-buildpackage. I got the following error:
**Unmet build dependencies: lv2core lv2-extensions-good**

so I tried sudo apt-get install. lv2core was fine. lv2-extensions-good was an issue, I got an error saying:
**Package lv2-extensions-good is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  lv2-dev:i386 lv2-dev**

So I did sudo apt-get install for lv2-dev which worked, but I still get an error:
**Unmet build dependencies: lv2-extensions-good**

How do I get around that?

**Comment by jeremysalwen** [comment]
The real dependency here is on the LV2 MIDI extension, which would be packaged in lv2-extensions-good if you had it.

**Comment by jeremysalwen** [comment]
With the recent version 1.5 release, the dependencies have been updated, and should work without lv2-extensions-good.
